In [1]:
import numpy as np #kutibxonani o'rnatish 

In [14]:
arr = np.array([1,2,3,4]) #array matritsa yaratish 

In [15]:
arr 

array([1, 2, 3, 4])

In [16]:
arr1 = np.array([[1,3,4],[1,2,3]]) #ikki o'lchovliy matritsa

In [19]:
arr1.ndim #necha o'lchavligini ko'rish

2

In [29]:
#indexlar bilan ishlash 

arr[0] #arrayning birinchi elementiga murojat qilish.
print(arr[0]+arr[1])

#birqancha o'lchovliy matritsalar bilan ishlash 

print(arr1[0,1]) #buyer da 0 araynig birnchi o'lchami 1 esa uning 2 elementi 
 #uch o'lchovliy arraylar bilan ishlash 

arr3 = np.array([[[1,2,3,4,5],[1,3,99,5,6]],[[1,2,3,4,5],[1,3,4,5,6]]])
print(f"Array {arr3} liy ")
print(arr3[0,1,2] ,"Biz qidirayotgan son") #arrayga murojat qilishda katta matritsadan boshlab boshlab murojat qilishni boshleymiz
 

3
3
Array [[[ 1  2  3  4  5]
  [ 1  3 99  5  6]]

 [[ 1  2  3  4  5]
  [ 1  3  4  5  6]]] liy 
99 Biz qidirayotgan son


In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[0,1,2]

6

In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) # yoki - orqali teskarisigaham murojat qilish mumkin 

Last element from 2nd dim:  10


In [42]:
# NumPy Array Slicing  Qirqib olish 
# [start:end] 
# [start:end:step] 

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6]) #ikkinchi elementdan boshlab to 5 elementgacha bolgan qiymatlarni ajratib oldi
print(arr[:6]) #toki 6 indexdagi qiymatgacha bo'lgan barcha qiymatni ajratib beradi
print(arr[:6:2]) # necha qadamda qiymatlarni olishiniham berish mumkin.
print(arr[-3:-1]) #orqadanham murojat qilish mumkin.
print(arr[::2]) #barcha qiymatda ikki qadam bilan murojat qiladi.

[2 3 4 5 6]
[1 2 3 4 5 6]
[1 3 5]
[5 6]
[1 3 5 7]


In [43]:
#Slicing 2-D Arrays

In [47]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])  #birinchi aynan nechinchisiga murojat qilish kerakligini ko'rsatamiz , song qayerdan qayergacha ekanligini beramiz
print(arr[0:2, 2])  # buyerda biz birinchi boliob qatorlarni ragisini beryapmiz song ustuni qiymatini beryapmiz 

[7 8 9]
[3 8]


In [48]:
#Data Types in Python

# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j



In [49]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype) #array type int32  ekanligini ko'rish mumkin 

int32


In [50]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) #buyerda unicode string ekanligini ko'ryapmiz

<U6


In [55]:
#Creating Arrays With a Defined Data Type 
#biz o'zimiz datatype ni berishimizham mumkin , bu uchun biz dtype dan foyalanamiz 

arr = np.array([2,20,2020] ,dtype = "S")
arr.dtype

dtype('S4')

In [57]:
#cope 
arr = np.array([1,2,3,4,5,6,7]) 
x = arr.copy() #asildan nushalab olmoqdamiz 
arr[3] = 50 #3chi indexdagi elementni qiymatini 50 qilib o'zgariri oldik
print(arr)
print(x)

[ 1  2  3 50  5  6  7]
[1 2 3 4 5 6 7]


In [59]:
#view
arr = np.array([1,2,3,4,5,6,7]) 
y = arr.view() #agar view orqali nusha olsak asil arrayda bo'lgan o'zgariishlar nushalangan arraygaham tasir qiladi.
arr[3] = 30

print(arr)
print(y)



[ 1  2  3 30  5  6  7]
[ 1  2  3 30  5  6  7]


In [60]:
# Shape of an Array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape #matritsalrni o'lchamini ko'rish mumkin. bizda 2 qator va 4 ta ustundan tashkil topgan 

(2, 4)

In [63]:
arr = np.array([1,2,3,4,5], ndmin = 24)
arr.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5)

In [67]:
#Reshape From 1-D to 2-D 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr.reshape(4,4)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [66]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) #ikkiga uchliy matritsadan 2 ta 

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [70]:
#agar siz nechta o'lchamga bolishni aniq bilmasez -1 dan foydalanizsh mumkin , masslan bunday 

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr.reshape(4,2 , -1) #buyerda o'zi teng taqsimlab beradi 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [71]:
#istalgan ko'p o'lchamliy arrayni bir o'lchami ga o'tkazish mumkih.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr.reshape(-1) #-1 berishni o'zi yetarliy

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [74]:
for x in np.nditer(arr):
  print(x)

1
2
3


In [77]:
#join arraylarni qo'shish 

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
x =np.concatenate((arr1,arr2))
x

array([1, 2, 3, 4, 5, 6])

In [79]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1) # bir qancha o'lchovliy arraylarni qo'shish va buyerda axis =1 ustun bo'yicha qoshyapti axis = 0 bo'lsa qator bo'yicha qo'shadi .

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
